### ISSUE TITLE
5.2 plugin don't compile

### ISSUE THREAD

**Issue by AliziaKaline** [mordentral/AdvancedSessionsPlugin#72]
Hi !

The plugin don't compile in 5.2.

"Plugins\AdvancedSteamSessions\Intermediate\Build\Win64\UnrealEditor\Inc\AdvancedSteamSessions\UHT\SteamRequestGroupOfficersCallbackProxy.gen.cpp(8): fatal error C1083: Impossible d'ouvrir le fichier include : 'Plugins/AdvancedSteamSessions/Source/AdvancedSteamSessions/Classes/SteamRequestGroupOfficersCallbackProxy.h' : No such file or directory"

Tried from source and launcher, no difference.

**Comment by mordentral** [comment]
That file literally exists in the repo and your error is in the engines auto generated files. If you are updating to 5.2 regenerate project files.

If that still doesn't fix it make sure you aren't over the OS's file name length limit (move the project to a folder closer to the root of your HDD).
